version: 2

models:

  - name: fct_orders
    description: "Table de faits principale"
    columns:

      - name: order_id
        description: "Identifiant unique (PK)"
        data_tests:
          - unique
          - not_null

      - name: status
        description: "Statut de la commande"
        data_tests:
          - not_null

      - name: customer_id
        description: "Clé étrangère"
        data_tests:
          - not_null

      - name: order_amount
        description: "Montant en euros"
        data_tests:
          - not_null

      - name: order_segment
        description: "low_value / mid_value / high_value"

      - name: country
        description: "Pays du client"

      - name: order_date
        description: "Date de la commande"

  - name: dim_customers
    description: "Dimension clients"
    columns:

      - name: customer_id
        description: "Identifiant unique (PK)"
        data_tests:
          - unique
          - not_null

      - name: email
        description: "Email normalisé"
        data_tests:
          - unique
          - not_null

      - name: total_orders
        description: "Nombre total de commandes"

      - name: total_spent_eur
        description: "Montant total dépensé"