version: 2

models:

  - name: fct_orders
    description: "Table de faits principale"
    columns:

      - name: order_id
        data_tests:
          - unique
          - not_null

      - name: status
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - placed
                  - shipped
                  - delivered
                  - returned
                  - cancelled

      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

      - name: order_amount
        data_tests:
          - not_null

  - name: dim_customers
    description: "Dimension clients"
    columns:

      - name: customer_id
        data_tests:
          - unique
          - not_null

      - name: email
        data_tests:
          - unique
          - not_null